<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-O9M6KMN" failures="1" tests="1" name="Default test(failed)" time="189.506" errors="0" timestamp="15 Feb 2022 14:22:41 GMT">
  <testcase classname="cs.qa.te.tests.NetworkForwarderToSupplierPageTest" name="validateForwarderNetworkSupplierExportNotesCertificate" time="132.372">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [[KD, KD 56ºC 30min, srm_showcase_88_1644488925_734395_timber_purchase_order_p1610_88.pdf, 10/02/2022, , CE, CE, srm_showcase_88_1644837388_523610_timberdocs_55910_timber_proforma_p1164_325.pdf, 14/02/2022, ]] but found [[]]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [[KD, KD 56ºC 30min, srm_showcase_88_1644488925_734395_timber_purchase_order_p1610_88.pdf, 10/02/2022, , CE, CE, srm_showcase_88_1644837388_523610_timberdocs_55910_timber_proforma_p1164_325.pdf, 14/02/2022, ]] but found [[]]
at cs.qa.te.tests.NetworkForwarderToSupplierPageTest.validateForwarderNetworkSupplierExportNotesCertificate(NetworkForwarderToSupplierPageTest.java:123)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- validateForwarderNetworkSupplierExportNotesCertificate -->
  <testcase classname="cs.qa.te.tests.NetworkForwarderToSupplierPageTest" name="validateForwarderNetworkSupplierInformation" time="0.0">
    <ignored/>
  </testcase> <!-- validateForwarderNetworkSupplierInformation -->
  <testcase classname="cs.qa.te.tests.NetworkForwarderToSupplierPageTest" name="validateForwarderNetworkSupplierProfile" time="0.0">
    <ignored/>
  </testcase> <!-- validateForwarderNetworkSupplierProfile -->
</testsuite> <!-- Default test(failed) -->
