<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="26" total="27" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-13T16:36:39Z" name="Default suite" finished-at="2023-01-13T16:40:13Z" duration-ms="213442">
    <groups>
    </groups>
    <test started-at="2023-01-13T16:36:39Z" name="Default test" finished-at="2023-01-13T16:40:13Z" duration-ms="213442">
      <class name="cs.qa.te.tests.SupplyPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:cs.qa.te.tests.SupplyPageTest@61dd025]" started-at="2023-01-13T16:36:39Z" name="setUp" finished-at="2023-01-13T16:36:45Z" duration-ms="5803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="loginPageTest()[pri:0, instance:cs.qa.te.tests.SupplyPageTest@61dd025]" started-at="2023-01-13T16:36:45Z" name="loginPageTest" finished-at="2023-01-13T16:37:30Z" duration-ms="44769" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTest -->
        <test-method signature="validateDownloadContractInvoicePOAndProformaFromActiveDeals()[pri:20, instance:cs.qa.te.tests.SupplyPageTest@61dd025]" started-at="2023-01-13T16:37:30Z" name="validateDownloadContractInvoicePOAndProformaFromActiveDeals" finished-at="2023-01-13T16:40:12Z" duration-ms="162565" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
ExcelType : Failed   expected [true] but found [false],
SupplierPhone : Failed   expected [true] but found [false],
SpecificationGS1 : Failed   expected [true] but found [false],
SpecificationModel : Failed   expected [true] but found [false],
SpecificationHSCode : Failed   expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
ExcelType : Failed   expected [true] but found [false],
SupplierPhone : Failed   expected [true] but found [false],
SpecificationGS1 : Failed   expected [true] but found [false],
SpecificationModel : Failed   expected [true] but found [false],
SpecificationHSCode : Failed   expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at cs.qa.te.tests.SupplyPageTest.validateDownloadContractInvoicePOAndProformaFromActiveDeals(SupplyPageTest.java:811)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDownloadContractInvoicePOAndProformaFromActiveDeals -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:cs.qa.te.tests.SupplyPageTest@61dd025]" started-at="2023-01-13T16:40:12Z" name="tearDown" finished-at="2023-01-13T16:40:13Z" duration-ms="292" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- cs.qa.te.tests.SupplyPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
